---
title: "__Zusammenfassung der Experimente und Auswertung__"
output: html_notebook
---

## __Charakterisierung der Bauteile__

### __Linearpolarisatoren__

#### __Experiment__
Aufbau/Durchführung

#### __Auswertung__
Wie erfolgt Auswertung?

##### __Linearpolarisator P1__
Plot/Diskussion

##### __Linearpolarisator P2__
Plot/Diskussion

##### __Linearpolarisator P3__
Plot/Diskussion

### __Wellenplatten__

#### __Experiment__
Aufbau/Durchführung

#### __Auswertung__
Wie erfolgt Auswertung?

##### __Wellenplatte W1__
Plot/Diskussion

##### __Wellenplatte W2__
Plot/Diskussion

### __Optische Fasern__

#### __Experiment__
Aufbau/Durchführung

#### __Auswertung__
Wie erfolgt Auswertung?

##### __PM-Faser F1__
Plot/Diskussion

##### __SM-Faser F2__
Plot/Diskussion

##### __MM-Faser F3__
Plot/Diskussion

### __WiTec-Detektor__

#### __Experiment__
Aufbau/Durchführung

#### __Auswertung__
Wie erfolgt Auswertung?
Plot/Diskussion/Mit und ohne Mikriskop


## __Polarisaionsabhängige Ramanspektroskopie am WiTec__
Aufbau/Durchführung

### __Ramanspektren von Tetrachlormethan__
Plot/Diskussion