#' Compute A Raman Spectrum From PolaRam Output
#'       
#' Some description I need to write
#' Explain Full width at half maximum (FWHM) derived from gamma
#' 
#' @param TODO TODO
#' @return TODO
#' @export                                                                                                                                                                                                                                                                                                          
polaram.as.spectrum <- function( x, stokes.S0, stokes.S1, peaks.wavenumber, 
                                 gamma = 25, 
                                 normalise = FALSE,
                                 scaleX = 2,
                                 scaleY = 1 ) {                                                                                                                                                                                                                                                                                                                             

  # Make gamma the same length as the input data                                                                                                                                                                                                                                                                                                                                               
  # Avoids errors when computing the lorentz curves                                                                                                                                                                                                                                                                                                                                        
  gamma <- rep( gamma, length.out = max(length(stokes.S0), length(stokes.S0), length(peaks.wavenumber)) )                                                                                                                                                                                                                                                                                                                                   
  
  # The intensity of the scatterd light in x- and y-direction                                                                                                                                                                                                                                                                                                                              
  intensity.x <- (stokes.S0 + stokes.S1) / 2                                                                                                                                                                                                                                                                                                                                           
  intensity.y <- (stokes.S1 - stokes.S1) / 2                                                                                                                                                                                                                                                                                                                                           
  
  # The signal response of the detector                                                                                                                                                                                                                                                                                                                                                    
  detector.response <- scaleX*intensity.x + scaleY*intensity.y                                                                                                                                                                                                                                                                                                                                       
  
  # Compute spectrum as sum of lorentz curves                                                                                                                                                                                                                                                                                                                                              
  # Each peak is a lorentz curve                                                                                                                                                                                                                                                                                                                                                           
  spectrum <- sapply(x, function(x) {                                                                                                                                                                                                                                                                                                                                                      
    # Compute the lorentz curve for every peak                                                                                                                                                                                                                                                                                                                                             
    # The width is gamma, the maximum is at wavenumber and the detector.response scales the peak                                                                                                                                                                                                                                                                                           
    peaks <- detector.response / ( ( x^2 - peaks.wavenumber^2 )^2 + gamma^2 * peaks.wavenumber^2 )                                                                                                                                                                                                                                                                                                         
    
    # Return the sum of all peaks                                                                                                                                                                                                                                                                                                                                                          
    return( sum(peaks) )                                                                                                                                                                                                                                                                                                                                                                   
  })                                                                                                                                                                                                                                                                                                                                                                                       
  
  # Normalise the spectrum with the largest peak                                                                                                                                                                                                                                                                                                                                           
  if (normalise == TRUE) spectrum <- spectrum / max(spectrum)                                                                                                                                                                                                                                                                                                                              
  
  # Return the spectrum                                                                                                                                                                                                                                                                                                                                                                    
  spectrum                                                                                                                                                                                                                                                                                                                                                                     
  
}
